job-android:

  stage: build
  tags: [ "docker-android" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-android/bc-dev-android:29

  script:
    - ./gradlew app:dependencies | grep org.linphone
    - ./gradlew assembleDebug
    - cp ./app/build/outputs/apk/debug/app-debug.apk lindoor-debug-unsigned.apk

  artifacts:
    paths:
      - lindoor-debug-unsigned.apk 
    when: always
    expire_in: 1 week

